# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cd5e0dbff638eaf534fd30a91f55d539a0b9e774d4193b9d5b016cf0b584fc5b236a8a98bbe0d75f9284f0f90a253a995ec04d0110adc68df6383da3041e746

test:
  secret_key_base: 9dc8fa480de9ee27401145eb345c7b8b478600e4b939bcf37bc58cc5664e7b96b8b44ff0d373c4c6d763cf2da5e709301e73528e94d91f2e7011f023c94d705d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
